const questionsData = [
    {
      category: "Gaming",
      questions: [
        ["What game do you always recommend?", "What game do you always warn people about?"],
        ["Which game had the best ending?", "Which game had the worst ending?"],
        ["Which game has the best soundtrack?", "Which game has the most annoying soundtrack?"],
        ["What’s the most addictive game you've played?", "What’s the most frustrating game you've played?"],
        ["Which gaming company do you respect the most?", "Which gaming company do you distrust the most?"],
        ["Which game has the best graphics?", "Which game has the worst art style?"],
        ["What’s the most overrated game?", "What’s the most underrated game?"],
        ["Which game has the best online community?", "Which game has the most toxic community?"],
        ["Which game deserves a remake?", "Which game should never be remade?"],
        ["Which game made you emotional?", "Which game made you rage the most?"],
        ["What’s your favorite gaming genre?", "What’s your least favorite gaming genre?"],
        ["What’s the best battle royale game?", "What’s the worst battle royale game?"],
        ["Which game had the best plot twist?", "Which game had the worst story?"],
        ["Which game do you replay the most?", "Which game do you regret buying?"],
        ["Which game character would you want to be?", "Which game character do you find annoying?"],
        ["What’s the best console ever?", "What’s the worst console ever?"],
        ["Which multiplayer game is the best?", "Which multiplayer game is the most frustrating?"],
        ["Which game has the best level design?", "Which game has the worst level design?"],
        ["What’s your favorite indie game?", "What’s an indie game you didn’t like?"],
        ["Which game deserves a sequel?", "Which game should never get a sequel?"],
        ["Which game series is the best?", "Which game series is overrated?"],
      ]
    },
    {
      category: "Movies & TV Shows",
      questions: [
        ["Which movie has the best plot twist?", "Which movie had the most predictable plot?"],
        ["Which TV show do you wish had another season?", "Which TV show dragged on for too long?"],
        ["What’s a movie everyone loves but you don’t?", "What’s a movie you love that everyone hates?"],
        ["What’s the best animated movie?", "What’s the worst animated movie you've seen?"],
        ["Which director always delivers great movies?", "Which director is overhyped?"],
        ["Which movie has the best plot twist?", "Which movie had the most predictable plot?"],
        ["Which TV show do you wish had another season?", "Which TV show dragged on for too long?"],
        ["What’s a movie everyone loves but you don’t?", "What’s a movie you love that everyone hates?"],
        ["What’s the best animated movie?", "What’s the worst animated movie you've seen?"],
        ["Which actor never disappoints?", "Which actor is overrated?"],
        ["What’s the best comedy movie?", "What’s the least funny comedy movie?"],
        ["Which movie had the best visual effects?", "Which movie had the worst CGI?"],
        ["What’s a show you binge-watched?", "What’s a show you gave up on?"],
        ["Which director is a genius?", "Which director is overhyped?"],
        ["Which horror movie is the scariest?", "Which horror movie was just laughable?"],
        ["What’s the best superhero movie?", "What’s the worst superhero movie?"],
        ["Which TV show has the best intro?", "Which TV show has the most annoying intro?"],
        ["Which movie character would you want to be?", "Which movie character annoys you the most?"],
        ["What’s the best TV show of all time?", "What’s the most overrated TV show?"],
        ["Which movie had the best soundtrack?", "Which movie had the most forgettable music?"],
        ["What’s a movie you’ve watched multiple times?", "What’s a movie you could never rewatch?"],
        ["Which movie has the best action scenes?", "Which movie has the worst fight choreography?"],
        ["Which TV show had the best series finale?", "Which TV show had the worst ending?"],
        ["What’s your favorite sci-fi movie?", "What’s the worst sci-fi movie you’ve seen?"],
      ]
    },
    {
      category: "Food & Drinks",
      questions: [
        ["What’s a weird food combination that you love?", "What’s a weird food combination that disgusts you?"],
        ["What’s the best street food you've ever had?", "What’s the worst fast food meal you've ever had?"],
        ["What’s your go-to comfort food?", "What’s a food that reminds you of bad memories?"],
        ["Which restaurant do you swear by?", "Which restaurant was the biggest disappointment?"],
        ["Which drink do you always order?", "Which drink do you regret ever trying?"],
      ]
    },
    {
      category: "Sports & Fitness",
      questions: [
        ["Who is the greatest athlete of all time?", "Who is the most overrated athlete?"],
        ["What’s the most exciting sport to watch?", "What’s the most boring sport to watch?"],
        ["Which sport has the best fans?", "Which sport has the most toxic fans?"],
        ["What’s the best team in history?", "What’s the most disappointing team ever?"],
        ["Which athlete has the best personality?", "Which athlete do you find arrogant?"],
      ]
    },
    {
      category: "Travel & Adventure",
      questions: [
        ["What’s a place you’d visit again?", "What’s a place you’d never go back to?"],
        ["What’s the most underrated travel destination?", "What’s the most overrated travel destination?"],
        ["What’s your best travel memory?", "What’s your worst travel experience?"],
        ["Which country has the best food?", "Which country has the most underwhelming food?"],
        ["What’s the best thing about traveling?", "What’s the worst part about traveling?"],
      ]
    },
    {
      category: "Technology & Gadgets",
      questions: [
        ["Which tech company do you trust the most?", "Which tech company do you think is the most unethical?"],
        ["What’s the best phone you've ever owned?", "What’s the worst phone you've ever owned?"],
        ["Which app do you use the most?", "Which app do you regret downloading?"],
        ["What’s the best gaming console ever?", "What’s the worst gaming console ever?"],
        ["Which futuristic technology excites you the most?", "Which futuristic technology scares you the most?"],
      ]
    },
    {
      category: "Personality & Opinions",
      questions: [
        ["What’s a habit you admire in people?", "What’s a habit that annoys you?"],
        ["What’s the best compliment you've received?", "What’s the worst insult you've received?"],
        ["What’s a skill you’re proud of?", "What’s a skill you wish you had?"],
        ["What’s your biggest strength?", "What’s your biggest weakness?"],
        ["What’s a piece of advice you always follow?", "What’s a piece of advice you think is terrible?"],
        ["What’s a habit you admire in people?", "What’s a habit that annoys you?"],
        ["What’s the best compliment you've received?", "What’s the worst insult you've received?"],
        ["What’s a skill you’re proud of?", "What’s a skill you wish you had?"],
        ["What’s your biggest strength?", "What’s your biggest weakness?"],
        ["What’s a piece of advice you always follow?", "What’s a piece of advice you think is terrible?"],
        ["What’s your best personality trait?", "What’s your most embarrassing trait?"],
        ["What’s the best thing about you?", "What’s the worst thing about you?"],
        ["What’s something you’re really good at?", "What’s something you absolutely suck at?"],
        ["Which quality do you admire most in others?", "Which quality do you dislike in others?"],
        ["What’s something people always assume about you?", "What’s something people never guess about you?"],
        ["What’s a fear you’ve overcome?", "What’s a fear you still struggle with?"],
        ["What’s your biggest motivation?", "What’s your biggest distraction?"],
        ["What’s the best decision you've made?", "What’s the worst decision you've made?"],
        ["What’s something you’re proud of?", "What’s something you regret?"],
        ["What’s your most unique trait?", "What’s your most relatable trait?"],
      ]
    },
    {
      category: "Random & Fun",
      questions: [
        ["If you could have dinner with any celebrity, who would it be?", "If you could ban any celebrity from TV, who would it be?"],
        ["What’s the best party you've been to?", "What’s the most awkward party experience you've had?"],
        ["What’s the funniest thing you've ever witnessed?", "What’s the most embarrassing thing that’s happened to you?"],
        ["If you could live in any fictional universe, which one would it be?", "If you could erase one fictional universe from existence, which one would it be?"],
        ["What’s your go-to joke?", "What’s the worst joke you've ever heard?"],
      ]
    },
    {
        category: "Numbers",
        questions: [
          ["How many countries have you visited?", "Pick a number between 5 and 50"],
          ["How many books do you read in a year?", "Pick a number between 0 and 100"],
          ["What's your ideal room temperature in Celsius?", "Pick a number between 15 and 30"],
          ["How many hours of sleep do you need to feel rested?", "Pick a number between 4 and 12"],
          ["How many siblings do you have?", "Pick a number between 0 and 10"],
          ["What's the maximum number of unread emails in your inbox?", "Pick a number between 0 and 10,000"],
          ["How many times have you moved houses?", "Pick a number between 0 and 20"],
          ["What percentage would you give your current happiness?", "Pick a number between 0 and 100"],
          ["How many languages do you speak fluently?", "Pick a number between 1 and 10"],
          ["How many pets have you owned in your lifetime?", "Pick a number between 0 and 15"],
          ["What's your daily screen time in hours?", "Pick a number between 1 and 16"],
          ["How many pairs of shoes do you own?", "Pick a number between 1 and 50"],
          ["What's the longest you've gone without showering (in days)?", "Pick a number between 0 and 30"],
          ["How many concerts have you attended?", "Pick a number between 0 and 100"],
          ["What's your record for consecutive days working out?", "Pick a number between 0 and 365"],
          ["How many times have you been on an airplane?", "Pick a number between 0 and 500"],
          ["What's the most cups of coffee you've had in one day?", "Pick a number between 0 and 20"],
          ["How many plants do you own?", "Pick a number between 0 and 100"],
          ["What's your age when you had your first kiss?", "Pick a number between 0 and 30"],
          ["How many TV shows are you currently watching?", "Pick a number between 0 and 20"],
          ["What's the most text messages you've sent in one day?", "Pick a number between 0 and 500"],
          ["How many speeding tickets have you received?", "Pick a number between 0 and 15"],
          ["What's the longest phone call you've ever had (in minutes)?", "Pick a number between 0 and 600"],
          ["How many apps do you have installed on your phone?", "Pick a number between 10 and 300"],
          ["What's your record for movie marathons (movies watched back-to-back)?", "Pick a number between 1 and 10"],
          ["How many times have you changed your hairstyle this year?", "Pick a number between 0 and 12"],
          ["What's the most consecutive hours you've spent gaming?", "Pick a number between 0 and 24"],
          ["How many times have you been to the hospital?", "Pick a number between 0 and 50"],
          ["What's the most money you've spent in one shopping trip?", "Pick a number between 10 and 10,000"],
          ["How many times have you fallen in love?", "Pick a number between 0 and 10"],
          ["What's the longest you've ever slept (in hours)?", "Pick a number between 8 and 24"],
          ["How many times have you been late to work this month?", "Pick a number between 0 and 31"],
          ["What's the highest floor you've ever been on in a building?", "Pick a number between 1 and 200"],
          ["How many times have you cooked this week?", "Pick a number between 0 and 21"],
          ["What's your record for days without internet access?", "Pick a number between 0 and 365"],
          ["How many times have you dyed your hair?", "Pick a number between 0 and 50"],
          ["What's the most consecutive days you've worn the same outfit?", "Pick a number between 1 and 30"],
          ["How many times have you won a competition?", "Pick a number between 0 and 100"],
          ["What's your current streak of days exercising?", "Pick a number between 0 and 365"],
          ["How many times have you been to the beach this year?", "Pick a number between 0 and 52"],
          ["What's the most glasses of water you've drunk in one day?", "Pick a number between 0 and 20"],
          ["How many times have you been stung by a bee?", "Pick a number between 0 and 10"],
          ["What's the most consecutive hours you've spent reading?", "Pick a number between 0 and 12"],
          ["How many times have you changed jobs?", "Pick a number between 0 and 20"],
          ["What's the longest road trip you've taken (in hours)?", "Pick a number between 1 and 100"],
          ["How many times have you been to a wedding?", "Pick a number between 0 and 30"],
          ["What's the most consecutive days you've eaten the same meal?", "Pick a number between 1 and 30"],
          ["How many times have you broken a bone?", "Pick a number between 0 and 10"],
          ["What's the highest number of unread notifications you've ignored?", "Pick a number between 0 and 10,000"],
          ["How many times have you been swimming this year?", "Pick a number between 0 and 100"],
          ["What's the most money you've found on the ground?", "Pick a number between 0 and 500"],
          ["How many times have you been to a music festival?", "Pick a number between 0 and 20"],
          ["What's your current age?", "Pick a number between 1 and 120"],
          ["How many times have you voted in elections?", "Pick a number between 0 and 20"],
          ["What's the longest you've gone without checking your phone (in hours)?", "Pick a number between 0 and 168"],
          ["How many times have you been on a boat?", "Pick a number between 0 and 50"],
          ["What's the most consecutive days you've worked?", "Pick a number between 1 and 365"],
          ["How many times have you been to a different time zone?", "Pick a number between 0 and 50"],
          ["What's the highest number of unread texts you've accumulated?", "Pick a number between 0 and 1,000"],
          ["How many times have you been camping?", "Pick a number between 0 and 30"],
          ["What's the most expensive meal you've ever eaten (in dollars)?", "Pick a number between 10 and 5,000"],
          ["How many times have you been to a sporting event?", "Pick a number between 0 and 100"],
          ["What's the longest you've gone without speaking (in hours)?", "Pick a number between 0 and 72"],
          ["How many times have you been to a museum this year?", "Pick a number between 0 and 52"],
          ["What's the highest number of tabs you've had open at once?", "Pick a number between 1 and 500"],
          ["How many times have you been to a theme park?", "Pick a number between 0 and 30"],
          ["What's the most consecutive hours you've spent working?", "Pick a number between 0 and 24"],
          ["How many times have you been to a funeral?", "Pick a number between 0 and 20"],
          ["What's the most consecutive days you've gone without TV?", "Pick a number between 0 and 365"],
          ["How many times have you been to a zoo?", "Pick a number between 0 and 20"],
          ["What's the highest number of people you've texted in one day?", "Pick a number between 0 and 100"],
          ["How many times have you been to a circus?", "Pick a number between 0 and 10"],
          ["What's the most money you've spent on a single item of clothing?", "Pick a number between 10 and 5,000"],
          ["How many times have you been to a casino?", "Pick a number between 0 and 50"],
          ["What's the longest you've gone without eating (in hours)?", "Pick a number between 0 and 72"],
          ["How many times have you been to a library this year?", "Pick a number between 0 and 100"],
          ["What's the highest number of photos you've taken in one day?", "Pick a number between 0 and 1,000"],
          ["How many times have you been to a concert alone?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent on social media?", "Pick a number between 0 and 12"],
          ["How many times have you been to a comedy show?", "Pick a number between 0 and 30"],
          ["What's the highest number of steps you've taken in one day?", "Pick a number between 0 and 100,000"],
          ["How many times have you been to an art gallery?", "Pick a number between 0 and 30"],
          ["What's the longest you've gone without brushing your teeth (in hours)?", "Pick a number between 0 and 72"],
          ["How many times have you been to a parade?", "Pick a number between 0 and 20"],
          ["What's the most consecutive days you've worn jeans?", "Pick a number between 1 and 30"],
          ["How many times have you been to a farmers market?", "Pick a number between 0 and 100"],
          ["What's the highest number of emails you've sent in one day?", "Pick a number between 0 and 500"],
          ["How many times have you been to a movie theater alone?", "Pick a number between 0 and 50"],
          ["What's the most consecutive hours you've spent studying?", "Pick a number between 0 and 24"],
          ["How many times have you been to a karaoke night?", "Pick a number between 0 and 30"],
          ["What's the longest you've gone without drinking water (in hours)?", "Pick a number between 0 and 48"],
          ["How many times have you been to a book club?", "Pick a number between 0 and 50"],
          ["What's the highest number of people you've called in one day?", "Pick a number between 0 and 50"],
          ["How many times have you been to a house party?", "Pick a number between 0 and 100"],
          ["What's the most consecutive days you've gone without makeup?", "Pick a number between 0 and 365"],
          ["How many times have you been to a protest?", "Pick a number between 0 and 20"],
          ["What's the longest you've gone without sitting down (in hours)?", "Pick a number between 0 and 24"],
          ["How many times have you been to a science museum?", "Pick a number between 0 and 20"],
          ["What's the highest number of consecutive days you've journaled?", "Pick a number between 0 and 1,000"],
          ["How many times have you been to a poetry reading?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent driving?", "Pick a number between 0 and 24"],
          ["How many times have you been to a flea market?", "Pick a number between 0 and 50"],
          ["What's the longest you've gone without laughing (in hours)?", "Pick a number between 0 and 72"],
          ["How many times have you been to a ballet?", "Pick a number between 0 and 20"],
          ["What's the highest number of days you've traveled consecutively?", "Pick a number between 0 and 365"],
          ["How many times have you been to a rooftop party?", "Pick a number between 0 and 30"],
          ["What's the most consecutive hours you've spent painting?", "Pick a number between 0 and 24"],
          ["How many times have you been to a book signing?", "Pick a number between 0 and 20"],
          ["What's the longest you've gone without checking social media (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a silent disco?", "Pick a number between 0 and 10"],
          ["What's the highest number of books you've read in one month?", "Pick a number between 0 and 50"],
          ["How many times have you been to a midnight movie premiere?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent playing an instrument?", "Pick a number between 0 and 12"],
          ["How many times have you been to a wine tasting?", "Pick a number between 0 and 30"],
          ["What's the longest you've gone without using cash (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a costume party?", "Pick a number between 0 and 30"],
          ["What's the highest number of days you've gone without a shower?", "Pick a number between 0 and 30"],
          ["How many times have you been to a stand-up comedy show?", "Pick a number between 0 and 30"],
          ["What's the most consecutive hours you've spent gardening?", "Pick a number between 0 and 12"],
          ["How many times have you been to a escape room?", "Pick a number between 0 and 20"],
          ["What's the longest you've gone without caffeine (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a food festival?", "Pick a number between 0 and 30"],
          ["What's the highest number of days you've gone without leaving home?", "Pick a number between 0 and 365"],
          ["How many times have you been to a drive-in movie?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent writing?", "Pick a number between 0 and 24"],
          ["How many times have you been to a haunted house?", "Pick a number between 0 and 20"],
          ["What's the longest you've gone without your phone (in days)?", "Pick a number between 0 and 30"],
          ["How many times have you been to a county fair?", "Pick a number between 0 and 30"],
          ["What's the highest number of days you've gone without watching TV?", "Pick a number between 0 and 365"],
          ["How many times have you been to a paint night?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent meditating?", "Pick a number between 0 and 24"],
          ["How many times have you been to a trivia night?", "Pick a number between 0 and 50"],
          ["What's the longest you've gone without eating meat (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a silent retreat?", "Pick a number between 0 and 10"],
          ["What's the highest number of days you've gone without sweets?", "Pick a number between 0 and 365"],
          ["How many times have you been to a murder mystery dinner?", "Pick a number between 0 and 10"],
          ["What's the most consecutive hours you've spent coding?", "Pick a number between 0 and 24"],
          ["How many times have you been to a networking event?", "Pick a number between 0 and 50"],
          ["What's the longest you've gone without alcohol (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a board game night?", "Pick a number between 0 and 100"],
          ["What's the highest number of days you've gone without coffee?", "Pick a number between 0 and 365"],
          ["How many times have you been to a improv show?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent dancing?", "Pick a number between 0 and 12"],
          ["How many times have you been to a craft fair?", "Pick a number between 0 and 30"],
          ["What's the longest you've gone without social media (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a potluck dinner?", "Pick a number between 0 and 50"],
          ["What's the highest number of days you've gone without exercise?", "Pick a number between 0 and 365"],
          ["How many times have you been to a open mic night?", "Pick a number between 0 and 20"],
          ["What's the most consecutive hours you've spent shopping?", "Pick a number between 0 and 12"],
          ["How many times have you been to a car show?", "Pick a number between 0 and 20"],
          ["What's the longest you've gone without meat (in days)?", "Pick a number between 0 and 365"],
          ["How many times have you been to a poetry slam?", "Pick a number between 0 and 20"],
          ["What's the highest number of days you've gone without dairy?", "Pick a number between 0 and 365"],
          ["How many times have you been to a magic show?", "Pick a number between 0 and 10"],
          ["What's the most consecutive hours you've spent hiking?", "Pick a number between 0 and 24"],
        ]
      },
      {
        category: "Animals",
        questions: [
          ["What's your favorite wild animal?", "What animal would be the worst to encounter in the dark?"],
          ["Which animal best represents your personality?", "Which animal would be the most annoying roommate?"],
          ["What's the cutest baby animal?", "What animal has the weirdest babies?"],
          ["Which animal would you want as a giant pet?", "Which animal would be the most dangerous if it was horse-sized?"],
          ["What's the most intelligent animal?", "What's the dumbest-looking animal?"],
          ["Which animal has the best survival skills?", "Which animal would go extinct first in a zombie apocalypse?"],
          ["What's the most underrated animal?", "What's the most overrated animal?"],
          ["Which animal has the most unusual ability?", "Which animal has the most useless skill?"],
          ["What's the best animal to have in a survival situation?", "What animal would be completely useless in a survival situation?"],
          ["Which animal would win in an all-species battle royale?", "Which animal would betray its allies first in a war?"],
          ["What's the most majestic animal?", "What's the least majestic animal?"],
          ["Which animal has the best parenting skills?", "Which animal has the worst parents in nature?"],
          ["What's the most peaceful animal?", "What's the most unnecessarily aggressive animal?"],
          ["Which extinct animal should we bring back?", "Which extinct animal should definitely stay extinct?"],
          ["What's the most adaptable animal?", "What animal would die immediately if taken out of its habitat?"],
          ["Which animal has the best camouflage?", "Which animal has the worst camouflage?"],
          ["What's the most misunderstood animal?", "What's the most accurately feared animal?"],
          ["Which animal has the most unusual diet?", "Which animal has the most boring diet?"],
          ["What's the fastest animal you'd like to race?", "What's the slowest animal that could still beat you in a race?"],
          ["Which animal has the best lifespan?", "Which animal has the worst lifespan?"],
          ["What's the most loyal animal?", "What's the most treacherous animal?"],
          ["Which animal would be the best spy?", "Which animal would be the worst secret keeper?"],
          ["What's the most colorful animal?", "What's the most boring-looking animal?"],
          ["Which animal has the best night vision?", "Which animal is practically blind at night?"],
          ["What's the most romantic animal?", "What's the least romantic animal?"],
          ["Which animal has the strongest bite?", "Which animal has the weakest bite?"],
          ["What's the best animal to find in your backyard?", "What's the worst animal to find in your house?"],
          ["Which animal has the best migration story?", "Which animal has the most pointless migration?"],
          ["What's the most athletic animal?", "What's the laziest animal?"],
          ["Which animal would be the best teacher?", "Which animal would be the worst professor?"],
          ["What's the most cooperative animal?", "What's the most selfish animal?"],
          ["Which animal has the best senses?", "Which animal has the worst senses?"],
          ["What's the most surprising animal fact you know?", "What animal fact sounds fake but is true?"],
          ["Which animal would be the best comedian?", "Which animal would bomb at stand-up comedy?"],
          ["What's the most dramatic animal?", "What's the most boring animal?"],
          ["Which animal has the best natural armor?", "Which animal is the most defenseless?"],
          ["What's the most successful invasive species?", "What's the worst invasive species?"],
          ["Which animal would be the best musician?", "Which animal would be tone-deaf?"],
          ["What's the most flexible animal?", "What's the stiffest animal?"],
          ["Which animal has the best social structure?", "Which animal has the most chaotic society?"],
          ["What's the most photogenic animal?", "What's the least photogenic animal?"],
          ["Which animal would be the best detective?", "Which animal would ignore all the clues?"],
          ["What's the most poisonous animal you'd dare to handle?", "What's the most harmless-looking dangerous animal?"],
          ["Which animal has the best winter survival tactics?", "Which animal is least prepared for winter?"],
          ["What's the most unusual pet you've ever wanted?", "What's the worst possible animal to keep as a pet?"],
          ["Which animal would be the best astronaut?", "Which animal would panic in zero gravity?"],
          ["What's the most creative animal?", "What's the most unoriginal animal?"],
          ["Which animal has the best problem-solving skills?", "Which animal would fail the simplest maze?"],
          ["What's the most heroic animal?", "What's the most cowardly animal?"],
          ["Which animal would be the best chef?", "Which animal would burn everything it cooks?"],
          ["What's the most ancient-looking animal still alive?", "What's the most modern-looking ancient animal?"],
          ["Which animal has the best memory?", "Which animal would forget its own name?"],
          ["What's the most symbiotic animal?", "What's the most parasitic animal?"],
          ["Which animal would be the best politician?", "Which animal would start a revolution?"],
          ["What's the most climate-resilient animal?", "What's the most climate-vulnerable animal?"],
          ["Which animal has the best vocal range?", "Which animal has the most annoying voice?"],
          ["What's the most monogamous animal?", "What's the most promiscuous animal?"],
          ["Which animal would be the best firefighter?", "Which animal would accidentally start fires?"],
          ["What's the most playful animal?", "What's the most serious animal?"],
          ["Which animal has the best teamwork?", "Which animal would ruin every group project?"],
          ["What's the most regenerative animal?", "What's the most fragile animal?"],
          ["Which animal would be the best journalist?", "Which animal would spread fake news?"],
          ["What's the most heat-resistant animal?", "What's the most cold-resistant animal?"],
          ["Which animal has the best disguise?", "Which animal's disguise fools nobody?"],
          ["What's the most talkative animal?", "What's the quietest animal?"],
          ["Which animal would be the best therapist?", "Which animal would give the worst advice?"],
          ["What's the most cleanly animal?", "What's the filthiest animal?"],
          ["Which animal has the best engineering skills?", "Which animal would build collapsing structures?"],
          ["What's the most optimistic animal?", "What's the most pessimistic animal?"],
          ["Which animal would be the best bartender?", "Which animal would spike all the drinks?"],
          ["What's the most nomadic animal?", "What's the most sedentary animal?"],
          ["Which animal has the best immune system?", "Which animal gets sick constantly?"],
          ["What's the most generous animal?", "What's the greediest animal?"],
          ["Which animal would be the best librarian?", "Which animal would eat all the books?"],
          ["What's the most patient animal?", "What's the most impatient animal?"],
          ["Which animal has the best balance?", "Which animal would trip over nothing?"],
          ["What's the most fashionable animal?", "What's the least stylish animal?"],
          ["Which animal would be the best CEO?", "Which animal would bankrupt the company?"],
          ["What's the most endangered animal you care about?", "What's the least concerning extinct animal?"],
          ["Which animal has the best parenting style?", "Which animal has the most chaotic family dynamics?"],
          ["What's the most water-dependent animal?", "What's the most drought-resistant animal?"],
          ["Which animal would be the best scientist?", "Which animal would falsify research data?"],
          ["What's the most sun-loving animal?", "What's the most shade-loving animal?"],
          ["Which animal has the best hunting strategy?", "Which animal fails at hunting constantly?"],
          ["What's the most communal animal?", "What's the most solitary animal?"],
          ["Which animal would be the best artist?", "Which animal would paint nonsense?"],
          ["What's the most aerodynamic animal?", "What's the least aerodynamic animal?"],
          ["Which animal has the best earthquake survival skills?", "Which animal would panic during mild tremors?"],
          ["What's the most romantic animal mating ritual?", "What's the weirdest animal courtship?"],
          ["Which animal would be the best pilot?", "Which animal would crash immediately?"],
          ["What's the most heat-tolerant animal?", "What's the most cold-tolerant animal?"],
          ["Which animal has the best tool-use skills?", "Which animal would use tools incorrectly?"],
          ["What's the most family-oriented animal?", "What's the most independent animal?"],
          ["Which animal would be the best gardener?", "Which animal would destroy all the plants?"],
          ["What's the most light-sensitive animal?", "What's the most light-ignorant animal?"],
          ["Which animal has the best escape skills?", "Which animal gets trapped constantly?"],
          ["What's the most musical animal?", "What's the least musical animal?"],
          ["Which animal would be the best diplomat?", "Which animal would start wars accidentally?"],
          ["What's the most smell-sensitive animal?", "What's the least smell-sensitive animal?"],
          ["Which animal has the best nest-building skills?", "Which animal builds the worst nests?"],
          ["What's the most electric animal?", "What's the least conductive animal?"],
          ["Which animal would be the best hacker?", "Which animal would forget all passwords?"],
          ["What's the most radioactive-resistant animal?", "What's the most radiation-sensitive animal?"],
          ["Which animal has the best recycling habits?", "Which animal is the messiest?"],
          ["What's the most time-sensitive animal?", "What's the least time-aware animal?"],
          ["Which animal would be the best architect?", "Which animal would build unsafe structures?"],
          ["What's the most gravity-defying animal?", "What's the most gravity-bound animal?"],
          ["Which animal has the best problem-solving skills?", "Which animal would fail to open a door?"],
          ["What's the most weather-predicting animal?", "What's the least weather-aware animal?"],
          ["Which animal would be the best mathematician?", "Which animal would fail at basic counting?"],
          ["What's the most magnetic animal?", "What's the least magnetic animal?"]
        ]
      },
      {
        category: "Survival Scenarios",
        questions: [
          // Zombie Apocalypse
          ["Who would you trust to lead during a zombie outbreak?", "Who would accidentally start the zombie apocalypse?"],
          ["Which friend would craft the best weapons?", "Who would panic and waste all the ammo?"],
          ["Who would survive the longest in a zombie siege?", "Who would get bitten trying to pet a zombie?"],
          
          // Stranded on an Island
          ["Who would build the best shelter?", "Who would burn down the shelter for fun?"],
          ["Who would find edible food in the wild?", "Who would poison the group with toxic berries?"],
          ["Who would keep morale high?", "Who would start a mutiny over coconut分配?"],
          
          // Alien Invasion
          ["Who would decode alien technology?", "Who would accidentally trigger the mothership’s weapons?"],
          ["Who would negotiate with aliens?", "Who would insult the alien leader’s tentacles?"],
          ["Who would organize a resistance?", "Who would sell out humanity for alien WiFi?"],
          
          // Time Travel Disaster
          ["Who would fix a broken timeline?", "Who would erase themselves from existence?"],
          ["Who would blend into medieval times?", "Who would invent smartphones in 1200 AD?"],
          ["Who would stop a historical disaster?", "Who would accidentally kill their own ancestor?"],
          
          // Robot Uprising
          ["Who would disable the robot army’s core?", "Who would teach robots to hate humans?"],
          ["Who would outsmart an AI overlord?", "Who would volunteer to become a cyborg spy?"],
          ["Who would protect humanity’s last safe zone?", "Who would reprogram friendly robots to rebel?"],
          
          // Natural Disaster
          ["Who would survive a volcanic eruption?", "Who would fall into the lava for a selfie?"],
          ["Who would navigate a sinking ship?", "Who would overload the lifeboats with snacks?"],
          ["Who would lead survivors through a blizzard?", "Who would burn the last firewood for marshmallows?"],
          
          // Heist Gone Wrong
          ["Who would mastermind a casino robbery?", "Who would trigger the alarms by accident?"],
          ["Who would crack the vault’s security?", "Who would take a nap mid-heist?"],
          ["Who would negotiate with hostages?", "Who would accidentally lock the team in the vault?"],
          
          // Fantasy Betrayal
          ["Who would wield a magic sword against a dragon?", "Who would try to adopt the dragon as a pet?"],
          ["Who would break the evil king’s curse?", "Who would become the new dark lord?"],
          ["Who would unite warring kingdoms?", "Who would start a war over a potato?"],
          
          // Space Station Crisis
          ["Who would fix the oxygen system?", "Who would open the airlock for 'fresh space air'?"],
          ["Who would communicate with hostile aliens?", "Who would challenge them to a dance-off?"],
          ["Who would ration supplies for survival?", "Who would eat the last protein bar secretly?"],
          
          // High School Chaos
          ["Who would ace a pop quiz during a lockdown?", "Who would start a food fight in the cafeteria?"],
          ["Who would organize an escape plan?", "Who would graffiti their name on the principal’s car?"],
          ["Who would calm everyone during a blackout?", "Who would spread fake ghost stories?"]
        ]
      }
  ];
  
  export default questionsData;
  