const whoAnsweredData = [
  "What's the most embarrassing song on your playlist?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "What's a secret talent nobody here knows about?",
  "What's the worst fashion decision you've ever made?",
  "If you could swap lives with someone in this room for a day, who would it be?",
  "What's your most irrational fear?",
  "What's the weirdest thing you've ever eaten?",
  "If you had to delete all but 3 apps from your phone, which would you keep?",
  "What's something you pretend to hate but actually enjoy?",
  "What's your go-to karaoke song?",
  "If you could live in any fictional universe, which one would it be?",
  "What's the most childish thing you still do?",
  "What's a movie you can quote word for word?",
  "If you could have dinner with any historical figure, who would it be?",
  "What's your guilty pleasure TV show?",
  "What's the worst gift you've ever received?",
  "If you could master any skill instantly, what would it be?",
  "What's your most used emoji?",
  "What's the longest you've gone without showering?",
  "If you could only watch one movie for the rest of your life, what would it be?",
  "What's something you're surprisingly good at?",
  "What's the most expensive thing you've ever broken?",
  "If you could be famous for one thing, what would it be?",
  "What's your biggest pet peeve?",
  "What's the weirdest dream you remember having?",
  "If you could time travel, would you go to the past or future?",
  "What's a conspiracy theory you secretly believe?",
  "What's your comfort food?",
  "If you could have any superpower, what would it be?",
  "What's the most ridiculous thing you've cried about?",
  "What's your favorite smell?",
  "If you could rename yourself, what name would you choose?",
  "What's something you've never told your parents?",
  "What's the worst date you've ever been on?",
  "If you could eliminate one thing from your daily routine, what would it be?",
  "What's your most unpopular opinion?",
  "What's the strangest compliment you've ever received?",
  "If you had unlimited money, what's the first thing you'd buy?",
  "What's a lie you told that got way out of hand?",
  "What's your toxic trait?",
  "If you could live anywhere in the world, where would it be?",
  "What's something you collect?",
  "What's the worst haircut you've ever had?",
  "If you could only listen to one artist for the rest of your life, who would it be?",
  "What's your biggest fear about the future?",
  "What's something you're terrible at but love doing anyway?",
  "If you could change one thing about yourself, what would it be?",
  "What's the most spontaneous thing you've ever done?",
  "What's your favorite way to waste time?",
  "If you could have any animal as a pet (legal or not), what would it be?",
  "What's a hill you're willing to die on?",
  "What's your most controversial food opinion?",
  "If you could go back and change one decision in your life, what would it be?",
  "What's the weirdest habit you have?",
  "What's something you wish you'd started doing earlier in life?",
  "If you could instantly become an expert in one subject, what would it be?",
  "What's the most cringe thing you did as a teenager?",
  "What's your love language?",
  "If you had to pick one person to survive a zombie apocalypse with, who would it be?",
  "What's something that made you cry recently?",
  "What's your biggest regret?",
  "If you could relive one day of your life, which would it be?",
  "What's the strangest thing in your search history?",
  "What's your worst quality?",
  "If you could read minds for a day, whose mind would you read?",
  "What's something you do when you're alone that you'd never admit?",
  "What's the most trouble you got into as a kid?",
  "If you could switch bodies with someone for a week, who would it be?",
  "What's your biggest insecurity?",
  "What's something people assume about you that's completely wrong?",
  "If you could erase one memory, what would it be?",
  "What's the pettiest thing you've done?",
  "What's your toxic relationship red flag?",
  "If you could have a conversation with your younger self, what would you say?",
  "What's something you're judging everyone else for right now?",
  "What's the meanest thing you've ever said to someone?",
  "If you could know the absolute truth to one question, what would you ask?",
  "What's your most embarrassing moment?",
  "What's a secret you've kept from everyone in this room?",
  "If you could cancel one popular thing, what would it be?",
  "What's something you pretend to like to fit in?",
  "What's the worst lie you've ever told?",
  "If your house was on fire and you could only save one thing, what would it be?",
  "What's your biggest turn-off in a person?",
  "What's something that instantly ruins your mood?",
  "If you could go back to any age, what would it be and why?",
  "What's your most toxic personality trait?",
  "What's something you judge people for doing, but you do it too?",
  "If you could get revenge on one person without consequences, who would it be?",
  "What's the longest you've held a grudge?",
  "What's something you do that you know annoys others?",
  "If you could make one person disappear from your life, who would it be?",
  "What's your biggest turn-on in a person?",
  "What's something you're secretly proud of?",
  "If you could change one physical feature about yourself, what would it be?",
  "What's the most passive-aggressive thing you've done?",
  "What's something you wish people would stop asking you?",
  "If you could start a rumor about yourself, what would it be?",
  "What's your most annoying habit?",
  "What's something you do that would make people lose respect for you?",
  "If you could live someone else's life for a year, whose would it be?",
  "What's the last thing that made you genuinely angry?",
  "What's something you've stolen?",
  "If you could confess something anonymously, what would it be?",
  "What's the most selfish thing you've ever done?",
  "What's your biggest dealbreaker in a relationship?",
  "If you could say one thing to your ex, what would it be?",
  "What's something you wish you were brave enough to do?",
  "What's the worst rumor you've spread about someone?",
  "If you could switch lives with a celebrity, who would it be?",
  "What's something that scares you about yourself?",
  "What's your most embarrassing Google search?",
  "If you could take back one text message, which would it be?",
  "What's the biggest risk you've ever taken?",
  "What's something you've done that you swore you'd never do?",
  "If you could change careers right now, what would you do?",
  "What's your biggest 'what if' in life?",
  "What's the most pathetic thing you've done for attention?",
  "If you could undo one friendship, which would it be?",
  "What's something you're ashamed of?",
  "What's the worst thing you've said behind someone's back?"
];

export default whoAnsweredData;
